org: matiasmeneses  
service: api-s3

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 256MB)
    memorySize: 256
    timeout: 30
    iam:
        role: arn:aws:iam::037294426912:role/LabRole

functions:
    lista_buckets:
        handler: lista_buckets.lambda_handler
        memorySize: 512
        events:
            - http:
                  path: /s3/lista-buckets
                  method: get
                  cors: true
                  integration: lambda
    lista_objetos_bucket:
        handler: lista_objetos_bucket.lambda_handler
        events:
            - http:
                  path: /s3/bucket/lista-objetos
                  method: post
                  cors: true
                  integration: lambda
    create_bucket:
        handler: create_bucket.lambda_handler
        memorySize: 512
        events:
            - http:
                  path: /s3/bucket/create
                  method: post
                  cors: true
                  integration: lambda
    create_directory:
        handler: create_directory.lambda_handler
        events:
            - http:
                  path: /s3/bucket/create-directory
                  method: post
                  cors: true
                  integration: lambda
    upload_file:
        handler: upload_file.lambda_handler
        memorySize: 512
        events:
            - http:
                  path: /s3/upload
                  method: post
                  cors: true
                  integration: lambda
