org: matiasmeneses  
service: api-s3

provider:
    name: aws
    runtime: python3.12	
    # Default memory size for functions (default: 256MB)
    memorySize: 256
    timeout: 30
      iam:
        role: arn:aws:iam::344494306973:role/LabRole
        
functions:
    lista_buckets:
        handler: lista_buckets.lambda_handler
        memorySize: 512
        events:
            - http:
                  path: /s3/lista-buckets
                  method: get
                  cors: true
                  integration: lambda
    lista_objetos_bucket:
        handler: lista_objetos_bucket.lambda_handler
        events:
            - http:
                  path: /s3/bucket/lista-objetos
                  method: post
                  cors: true
                  integration: lambda
    create_bucket:
        handler: crear_bucket.lambda_handler
        memorySize: 512
        events:
            - http:
                  path: /s3/bucket/create
                  method: post
                  cors: true
                  integration: lambda
    create_directory:
        handler: crear_directory.lambda_handler
        events:
            - http:
                  path: /s3/bucket/create-directory
                  method: post
                  cors: true
                  integration: lambda
    upload_file:
        handler: subir_archivo.lambda_handler
        memorySize: 512
        events:
            - http:
                  path: /s3/upload
                  method: post
                  cors: true
                  integration: lambda
